name: todo_list
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.6
  floor: ^1.4.2
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  local_auth: ^2.2.0
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  intl: any
  loading_animation_widget: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  analyzer: ^5.0.0
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

