name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
    outputs:
      apk-artifact:
        description: "Android APK file"
        value: ${{ jobs.build.outputs.release-apk }}
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./todo_list
    env:
      APK_PATH: "./todo_list/build/app/outputs/flutter-apk/app-release.apk"
      AAB_PATH: "./todo_list/build/app/outputs/bundle/release/app-release.aab"
    outputs:
      apk-artifact: ${{ steps.artifact-upload.artifact-id}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java to compile Android
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.2"
          channel: 'stable'
      - name: Get dependencies
        run: dart pub get
      - name: Generate code
        run: dart run build_runner build
      - name: Start apk release build
        run: flutter build apk --no-pub --release
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: release-apk
          path: {{ APK_PATH }}
          retention-days: 5
        
