name: Android Release

on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/android-build.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
      - name: Display structure of downloads
        run: ls -R
      
       
